version: '3.8'

services:
  app:
    image: ghcr.io/lvshujun0918/ai_water:main
    ports:
      - "80:8080"
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./backend/users.db:/app/backend/users.db
    environment:
      - NODE_ENV=production